"use client";
import {useEffect,useState} from "react";
import {Download,Check,Share} from "lucide-react";
import {Button} from "@/components/ui/button";
import {getInstallPrompt,rememberInstallPrompt,type InstallPrompt} from "@/lib/pwa-install";
export function InstallApp(){
 const [secure,setSecure]=useState<boolean|null>(null);
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null);const [installed,setInstalled]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const media=window.matchMedia("(display-mode: standalone)");const sync=()=>setInstalled(media.matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));queueMicrotask(()=>{sync();setSecure(window.isSecureContext);setPrompt(getInstallPrompt());});
 const available=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPrompt);};const done=()=>{setInstalled(true);setPrompt(null);};
 window.addEventListener("beforeinstallprompt",available);window.addEventListener("appinstalled",done);media.addEventListener("change",sync);
 return()=>{window.removeEventListener("beforeinstallprompt",available);window.removeEventListener("appinstalled",done);media.removeEventListener("change",sync);};},[]);
 return <div className="space-y-6"><section className="rounded-3xl bg-[var(--feature-surface)] p-7 text-white sm:p-10"><p className="font-label text-[var(--rotary-gold)]">Your club, one tap away</p><h2 className="font-heading mt-4 max-w-lg text-4xl font-semibold">Make room for Rotary.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-white/75">Add Road Town Rotary to your home screen. Open your diary, service projects and conversations in a dedicated app window.</p>{installed?<p className="mt-6 flex items-center gap-2 text-sm text-[var(--rotary-gold)]"><Check className="size-5" />You’re using the installed app.</p>:secure===false?<div role="status" className="mt-5 rounded-xl border border-white/25 bg-white/10 p-4"><p className="font-semibold text-[var(--rotary-gold)]">This address is for browsing, not full app installation.</p><p className="mt-2 text-sm leading-6 text-white/80">You’re using an HTTP address. Open the club’s HTTPS website on your phone to install the app. Changing http to https won’t work unless a trusted HTTPS server has been set up.</p></div>:prompt?<Button className="mt-6" disabled={pending} onClick={async()=>{setPending(true);setError("");try{await prompt.prompt();await prompt.userChoice;rememberInstallPrompt(null);setPrompt(null);}catch{setError("Use your browser’s install menu to try again.");}finally{setPending(false);}}}><Download className="size-4" />{pending?"Opening installer…":"Install app"}</Button>:<p className="mt-5 text-sm text-[var(--rotary-gold)]">On iPhone, use Safari’s Share menu → Add to Home Screen. Other browsers may offer installation in their menu.</p>}{error&&<p role="alert" className="mt-3 text-sm">{error}</p>}</section>
 {!installed&&secure!==false&&<div className="grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-6"><h3 className="font-heading flex items-center gap-2 text-xl"><Share className="size-5 text-primary" />iPhone & iPad</h3><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-6 text-muted-foreground"><li>Open the club’s website in Safari.</li><li>Tap Share, then Add to Home Screen.</li><li>If shown, turn on Open as Web App, then tap Add.</li></ol></section><section className="rounded-2xl border border-border bg-card p-6"><h3 className="font-heading text-xl">Android & desktop</h3><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-6 text-muted-foreground"><li>Open the club’s website in Chrome or Edge.</li><li>Tap Install app above when available, or open the browser menu.</li><li>Choose Install app or Add to Home screen and follow the prompts.</li></ol></section></div>}
 <p className="text-sm leading-7 text-muted-foreground">Use the club’s secure HTTPS website when installing on your phone. Your account stays the same. An internet connection is needed for member records and updates; the offline screen helps you reconnect.</p></div>;
}
